export const ActionTypes = {
  UPDATE_PRODUCT_LIST: "UPDATE_PRODUCT_LIST",
  SET_CURRENT_PRODUCT: "SET_CURRENT_PRODUCT",
  UPDATE_A_PRODUCT: "UPDATE_A_PRODUCT",
  DELETE_A_PRODUCT: "DELETE_A_PRODUCT",
  ADD_PRODUCT: "ADD_PRODUCT",
  UPDATE_LOADER: "UPDATE_LOADER",
  SIGN_IN: "SIGN_IN",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  SET_USER_LIST: "SET_USER_LIST",
  ADD_USER: "ADD_USER",
};
